os: osx
language: shell
sudo: false

notifications:
  email: never

install:
  - wget -O phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod +x phpunit
  - ./phpunit --version

script:
  - ./phpunit
  - shellcheck asimov *.sh

matrix:
  fast_finish: true
