os: osx
language: shell
sudo: false

notifications:
  email: never

install:
  - brew install composer shellcheck
  - composer install --prefer-dist --no-suggest

script:
  - composer test

matrix:
  fast_finish: true
